version: 2

refs:

  container: &container
    docker:
      - image: node:12
        environment:
          DATABASE_URL: 'postgres://test-user:123456@localhost:5432/test-db'
      - image: postgres:12-alpine
        environment:
          POSTGRES_USER: test-user
          POSTGRES_DB: test-db
          POSTGRES_PASSWORD: 123456

    working_directory: ~/repo

  steps:
    - &Install
      run:
        name: Install Dependencies
        command: npm install
    - &Run_Migrations
      run:
        name: Run migrations
        command: npm run migrations:test
    - &Test
      run:
        name: Test
        command: npm run test

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *Install
      - *Run_Migrations
      - *Test

  build-and-test:
    <<: *container
    steps:
      - checkout
      - *Install
      - *Run_Migrations
      - *Test
      - run: echo "Run migrations on staging db"
      - run: echo "Deploy to staging"
      - run: echo "Post to slack - deployment waiting for approval"
      - run:
          name: Post to Slack on FAILURE
          command: echo "Post to slack - staging build failed"
          when: on_fail
      - store_artifacts:
          path: coverage


workflows:
  version: 2
  master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
